version: "3.9"
services:
  ibmmqui:
    image: ibmcom/mq:latest
    container_name: ibmmqui
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=app
    ports:
      - "1414:1414"
      - "9443:9443"
    networks:
      - mqtest
    healthcheck:
      test: ["CMD", "curl", "-f",  "-k" , "https://ibmmqui:9443/ibmmq/console/login.html"]
      interval: 30s
      timeout: 10s
      retries: 5
  consumer:
    build:
      dockerfile: Dockerfile.producer
      context: .
    # container_name: producer
    command: gradle run -Dresource=/app/resource
    networks:
      - mqtest
    depends_on:
      ibmmqui:
        condition: service_healthy
  gatling:
    build:
      dockerfile: Dockerfile.producer
      context: .
    container_name: gatling
    command: gradle build gatlingRun -Dresource=/app/resource
    networks:
      - mqtest
    depends_on:
      ibmmqui:
        condition: service_healthy
    volumes:
      - ./build:/app/build
networks:
  mqtest:
    driver: bridge
